### ISSUE TITLE
git.branch showing HEAD, not branch name

### ISSUE THREAD

**Issue by alfanse** [n0mer/gradle-git-properties#109] opened 2018-06-22 12:36 UTC
I'm using gradle with:
```
plugins {
    id 'java'
    id 'maven'
    id "com.gorylenko.gradle-git-properties" version "1.4.21"
    id 'org.springframework.boot' version '2.0.3.RELEASE'
}

apply plugin: 'io.spring.dependency-management'

gitProperties {
    keys = ['git.branch','git.commit.id','git.commit.time']
}
```
and I noticed the /actuator/info endpoint has this
```
{
  "git": {
    "branch": "HEAD",
    "commit": {
      "id": "60b310b",
      "time": "2018-06-22T12:17:08Z"
    }
  }
}
```

i.e. branch is not the branch name!
I was expected "develop"

I'm using:
```
git --version
git version 2.14.1
```
```
./gradlew -v
Gradle 4.7
Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          10.0.1 ("Oracle Corporation" 10.0.1+10)
```

**Comment by tha2015** [comment] 2018-06-22 14:05
This issue is similar to issue #46 which was fixed in latest version v1.5.1
Can you try v1.5.1 and let us know if the issue is fixed? Thanks.

**Comment by tha2015** [comment] 2018-06-25 07:58
@alfanse  Hi, have you had a chance to test the issue with latest version? Thanks.

**Comment by tha2015** [comment] 2018-07-02 00:09
Closing because of no response

**Closed by tha2015** 2018-07-02 00:09 UTC

**Comment by spyro2000** [comment] 2021-06-16 08:12
I have the same problem with version 2.2.4 (build was done by GitLab):

![image](https://user-images.githubusercontent.com/8479925/122183205-4ba7db80-ce8b-11eb-9356-c2e9986e324b.png)
