### ISSUE TITLE
"gitRepositoryRoot" config doesn't work with 1.4.21

### ISSUE THREAD

**Issue by mrcasablr** [n0mer/gradle-git-properties#97] opened 2018-03-31 03:32 UTC
All i'm using this plugin with Gradle 4.6. With 1.4.20 it works. On upgrading to 1.4.21 it cannot find my .git directory as it is at the project root.  When I specify the `gotGitDirectory` it fails with the following error

```
* What went wrong:
A problem occurred evaluating root project 'api'.
> Could not set unknown property 'dotGitDirectory' for object of type com.gorylenko.GitPropertiesPluginExtension.
```

My `gitProperties` configuration looks like 
```
gitProperties {
    gitRepositoryRoot = new File("${project.rootDir}/..")
    dotGitDirectory = new File("${project.rootDir}/.git")
    dateFormat = "yyyy-MM-dd'T'HH:mmZ"
    dateFormatTimeZone = "Asia/Kolkata"
}
```
Here is my `build.gradle` configuration
```
dependencies {
                classpath( "org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}" )
                classpath( 'io.spring.gradle:dependency-management-plugin:1.0.4.RELEASE' )
                classpath( 'gradle.plugin.com.gorylenko.gradle-git-properties:gradle-git-properties:1.4.21' )
        }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'com.gorylenko.gradle-git-properties'
```
Do I have the correct configuration? Rolling back to 1.4.20 for now.

**Comment by tha2015** [comment] 2018-03-31 03:39
There is no "dotGitDirectory" config key in v1.4.21. Please check  https://github.com/n0mer/gradle-git-properties/tree/v1.4.21 for info about v1.4.21

The "dotGitDirectory" property is going to be available since v1.5.0 which is not released yet. I assume that you used the document at (https://github.com/n0mer/gradle-git-properties/tree/master) which is NOT the right document for v1.4.21

**Comment by mrcasablr** [comment] 2018-03-31 11:40
@tha2015  Thank you for the response. There is definitely a regression between 1.4.20 and 1.4.21.

The following code with 1.4.20 works.  
```
gitProperties {
    gitRepositoryRoot = new File("${project.rootDir}/..")
    dateFormat = "yyyy-MM-dd'T'HH:mmZ"
    dateFormatTimeZone = "Asia/Kolkata"
}
```

With 1.4.21, it breaks with error 
```
Execution failed for task ':generateGitProperties'.
> org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /home/mrcasablr/src/example/example-api/mgmt-api/api/.git
```
The `.git` repo is present at `/home/mrcasablr/src/example/example-api/mgmt-api` directory

**Comment by tha2015** [comment] 2018-03-31 14:57
There was a change to fix an issue regarding .git repo (see https://github.com/n0mer/gradle-git-properties/pull/50/commits/ee60dedaab83df28a6c1ed1ef0b2b0b412c52025 )

About your issue: it seems like the plugin tried to access mgmt-api/api/.git while the correct location is mgmt-api/.git. Can you try with gitRepositoryRoot='/home/mrcasablr/src/example/example-api/mgmt-api' to see if it works?

FYI. These kinds of issues will soon be gone in the next version (v1.5.0) which will have much better support for finding .git folder automatically and no manually config should be needed.

**Comment by mrcasablr** [comment] 2018-03-31 15:15
@tha2015  

`gitRepositoryRoot='/home/mrcasablr/src/example/example-api/mgmt-api'` did not help either.  Looks like it is looking for `.git` in the current folder than respecting the value of `gitRepositoryRoot`

**Comment by tha2015** [comment] 2018-03-31 15:31
Please post the full stacktrace of the exception (use --stacktrace option of Gradle) and relevant config in build.gradle . It would be helpful to resolve the issue.

I suspect that you have multiple Gradle subprojects and the plugin is applied from from the top project. If yes, then it is a bit tricky to configure.

**Comment by mrcasablr** [comment] 2018-03-31 15:52
There are no subprojects. Here is the relevant gradle config 
```
        dependencies {
                classpath( "org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}" ) 
                classpath( 'io.spring.gradle:dependency-management-plugin:1.0.4.RELEASE' )
                classpath( 'gradle.plugin.com.gorylenko.gradle-git-properties:gradle-git-properties:1.4.2
1' )
        }

}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot' 
apply plugin: 'io.spring.dependency-management'
apply plugin: 'com.gorylenko.gradle-git-properties'

gitProperties {
    //gitRepositoryRoot = new File("${project.rootDir}/..")
    gitRepositoryRoot = new File("/home/mrcasablr/src/example/example-api/mgmt-api")
    dateFormat = "yyyy-MM-dd'T'HH:mmZ"
    dateFormatTimeZone = "Asia/Kolkata"
}
```
Here is the stacktrace
```
[mrcasablr@localhost api]$ ./gradlew build --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateGitProperties'.
> org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /home/mrcasablr/src/example/example-api/mgmt-api/api/.git

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':generateGitProperties'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.UncheckedIOException: org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /home/mrcasablr/src/example/example-api/mgmt-api/api/.git
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:57)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:76)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:788)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:755)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        ... 30 more
Caused by: org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /home/mrcasablr/src/example/example-api/mgmt-api/api/.git
        at org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:582)
        at org.eclipse.jgit.api.Git.open(Git.java:117)
        at org.eclipse.jgit.api.Git.open(Git.java:99)
        at org.eclipse.jgit.api.Git$open.call(Unknown Source)
        at org.ajoberstar.grgit.operation.OpenOp.call(OpenOp.groovy:85)
        at org.ajoberstar.grgit.operation.OpenOp.call(OpenOp.groovy)
        at java_util_concurrent_Callable$call.call(Unknown Source)
        at org.ajoberstar.grgit.util.OpSyntaxUtil.tryOp(OpSyntaxUtil.groovy:45)
        at org.ajoberstar.grgit.Grgit$__clinit__closure1.doCall(Grgit.groovy:194)
        at com.gorylenko.GitPropertiesPlugin$GenerateGitPropertiesTask.generate(GitPropertiesPlugin.groovy:81)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        ... 42 more


* Get more help at https://help.gradle.org

BUILD FAILED in 1s
3 actionable tasks: 2 executed, 1 up-to-date
[mrcasablr@localhost api]$ 
```
Additional details
```
[mrcasablr@localhost api]$ ./gradlew --version
------------------------------------------------------------
Gradle 4.6
------------------------------------------------------------
Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_161 (Oracle Corporation 25.161-b14)
OS:           Linux 4.15.13-300.fc27.x86_64 amd64
```

**Comment by tha2015** [comment] 2018-04-01 06:06
This is the code from BaseRepositoryBuilder.java:582

```
581		if (isMustExist() && !repo.getObjectDatabase().exists())
582			throw new RepositoryNotFoundException(getGitDir());
```
I guess that your git repo doesn't have any commit (just initialized) or something is wrong with it.

Please try to run `$ git log` command from mgmt-api/api directory to see if anything wrong with it.

**Comment by tha2015** [comment] 2018-04-01 06:09
Thanks for the info. I will try to reproduce and will update later.

**Comment by tha2015** [comment] 2018-04-01 14:52
@mrcasablr You are correct. It is a bug in version of 1.4.21 
The change https://github.com/n0mer/gradle-git-properties/commit/ee60dedaab83df28a6c1ed1ef0b2b0b412c52025 made the plugin to evaluate the gitRepositoryRoot config too early in the process and so the configured value will not be used by the plugin.
This issue won't happen in the next version because I changed the logic recently to delay evaluating `dotGitDirectory` until it is being used.
Because of your feedback, I added more logging info for the plugin in the next version to support debugging. 
Thanks for the valuable feedbacks. It does help to improve the quality of the plugin. Let's wait for the next version with many improvements and bug fixes!

For the current version v1.4.21, I don't think `dotGitDirectory` can be used, so you will have to use the version of 1.4.20  if you need to configure it.

**Comment by tha2015** [comment] 2018-04-01 15:02
Fixed by commit https://github.com/n0mer/gradle-git-properties/commit/ac7e5fa7b7cfd147954d0788ea535693e2a5d618#diff-80b4dd1b196ae82a704a775404384321

**Closed** 2018-04-03 04:37 UTC
Labels: bug
