### ISSUE TITLE
Add ability to expose tags data

### ISSUE THREAD

**Issue by dima767** [n0mer/gradle-git-properties#65] opened 2018-03-19 21:03 UTC

**Comment by tha2015** [comment] 2018-03-19 21:25
Note: If this is about git.tags, then we already have issue #48 for it.

**Comment by dima767** [comment] 2018-03-19 22:04
Yeah, I just want to include the tags for HEAD at the time of build

**Comment by tha2015** [comment] 2018-03-20 02:57
Duplicate of issue #48. Will be closed.

**Closed by tha2015** 2018-03-20 02:57 UTC
