### ISSUE TITLE
Gradle 6.0.1 No signature of method: org.ajoberstar.grgit.service.BranchService.current()  

### ISSUE THREAD

**Issue by sdelamo** [n0mer/gradle-git-properties#140] opened 2019-12-18 06:13 UTC
I am getting an error when I apply the plugin to a Gradle 6.0.1 build. 

```
Execution failed for task ':api:generateGitProperties'.
> No signature of method: org.ajoberstar.grgit.service.BranchService.current() is applicable for argument types: () values: []
  Possible solutions: getCurrent(), collect(), print(java.io.PrintWriter), collect(groovy.lang.Closure), print(java.lang.Object), collect(java.util.Collection, groovy.lang.Closure)
```

**Comment by tha2015** [comment] 2019-12-18 14:20
I suspect that there is another plugin using a different git library and cause a version conflict. You can try to use v1.4.x to see if it fixes the issue (more info here https://github.com/n0mer/gradle-git-properties/issues/133#issuecomment-531011047 )
To have more info about the issue, can you run gradle with --stacktrace --debug and see what is the root cause?

**Comment by tha2015** [comment] 2020-02-09 05:06
This is not a bug. The other plugin is causing a version conflict.So closing this issue.

**Closed by tha2015** 2020-02-09 05:06 UTC
