### ISSUE TITLE
Support Gradle build cache

### ISSUE THREAD

**Issue by sdavids** [n0mer/gradle-git-properties#116] opened 2018-09-08 13:39 UTC
Please support Gradle build cache.

https://docs.gradle.org/current/userguide/build_cache.html#sec:task_output_caching_details

**Comment by CristianGM** [comment] 2018-09-11 21:58
I wonder how, this task is changing on every execution.

**Comment by tha2015** [comment] 2018-09-11 23:01
From my understanding, when building with "--build-cache" option, gradle will store task output artifacts (annotated by @Output , in this case, it is the generated git.properties file) into GRADLE_HOME and will copy stored files back to build folder if the task input (annotated by @Input) are the same as a previous cached entry. The idea is to try to reuse some cached output files to reduce the build time (assuming that the time to run the task is more than the time to calculate git properties).

BTW  have a question. Does anyone have a case where this task is so slow that we need to implement build case feature?

**Comment by CristianGM** [comment] 2018-09-12 06:09
You are right about how it work, but the issue is the input, would you use the `.git` folder as input?

About the `git.properties` what would be amazing is removing the comment with the timestamp so if I don't use the build.time the `git.properties` file would be the same for the same input.
That's not only because cacheable tasks need to have reproducible outputs, is because all the other tasks on the project are invalidating the task because this files changes at every build.

**Comment by sdavids** [comment] 2018-09-17 15:10
```
#Mon Sep 10 20:41:05 CEST 2018
git.build.time=2018-09-10T20\:41\:05+0200
```

These two lines are changed on every build, therefore one cannot support a [reproducible build](https://reproducible-builds.org).

How the Spring Boot plugin supports reproducible builds/gradle build cache:

> The default value for build.time is the instant at which the project is being built. A side-effect of this is that the task will never be up-to-date. [...] Another side-effect is that the task’s output will always change and, therefore, the build will not be truly repeatable.

https://docs.spring.io/spring-boot/docs/2.0.5.RELEASE/gradle-plugin/reference/html/#integrating-with-actuator-build-info

**Comment by sdavids** [comment] 2018-09-17 15:16
The input would be _git.commit.id_ in combination with _git.dirty_.

Also there should be a way to remove/null the following:

- git.build.host
- git.build.user.email
- git.build.user.name

In that way one can use a remote build cache.

**Comment by sdavids** [comment] 2018-09-17 15:23
_git.commit.id_ and _git.dirty_ should be the input to get cacheable/[reproducible](https://reproducible-builds.org) builds.

**Comment by tha2015** [comment] 2018-09-17 16:18
@sdavids I assume that this issue is needed (especially when using with remote build cache) because this task is generating new git.properties files every time, and as a result, the other tasks will execute again and will slow down the build process? Is that correct? 
@CristianGM Although the git.properties file contains timestamp inside, only the properties are compared and if there is no new change (excluding the comment), the git.properties will not be updated. I'm not sure in your case what is causing the invalidating other tasks. See (https://github.com/n0mer/gradle-git-properties/blob/master/src/main/groovy/com/gorylenko/PropertiesFileWriter.groovy#L45) for the logic when updating git.properties

**Comment by CristianGM** [comment] 2018-09-17 17:27
@tha2015 actually the issue is the file doesn't exist when you run the task on Travis-CI, so it changes every time.
Reproducible builds are important.

**Comment by tha2015** [comment] 2018-10-03 04:45
@sdavids  @CristianGM It looks like we need to implement this feature in  two steps: 1. make the build reproducible (same input must generate same input every time); 2. support build cache (i.e. add annotations to the task to allow Gradle to cache and reuse cached output if same input is found). 

Luckily Brane recently contributed PR #120 which will help to create reproducible builds. I will work with Brane to merge it soon. There is still one issue with the  generated properties file is the line ending are platform dependent because we depend on java Properties class to create the output (see newLine() calls at  http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/util/Properties.java#l841). So the output will be different when building on Windows vs Linux. 

What do you think?

**Comment by tha2015** [comment] 2019-01-10 15:38
Updated by commit ID 1d3a0abdba69d308338e27e0998478746e1f7eb3

**Comment by tha2015** [comment] 2019-01-10 21:16
Fixed in v2.0.0

**Closed by tha2015** 2019-01-10 21:16 UTC
Labels: enhancement

**Comment by deeTEEcee** [comment] 2019-07-12 22:51
just started using both gradle and this plugin. i don't really want the input/output to be a part of the gradle process and just want to generate the `git.properties file. is that an option somewhere?

**Comment by tha2015** [comment] 2019-07-12 23:02
My understanding is you don't want the "gradle build" command automatically generate git.properties for you? 
You can do that by removing the task dependency between generateGitProperties task and classes task as below:
`classes.dependsOn.remove("generateGitProperties")`
Note: I'm assuming that you are using java plugin in your build.gradle. If you don't use java plugin, you don't need to remove the task dependency.

Then you can use the task  "generateGitProperties" to generate git.properties as you want (either byc alling from command line, or add a task dependency to run it when another  task is called).

**Comment by deeTEEcee** [comment] 2019-07-13 00:05
I want to generate git.properties but I keep getting `Input property 'rootSpec$1' file ...git.properties has changed.` I don't want the git properties to affect any of my gradle tasks regardless of how the code changes. I'd like to leave that responsibility to the other tasks themselves and have `generateGitProperties` always be "up to date"

I've tried the following:
```
tasks.generateGitProperties {
output.upToDateWhen { true }
}
```
but when I add a new commit or change properties, it still has to update it again.

**Comment by tha2015** [comment] 2019-07-13 01:58
I guess it is because you didn't configure which properties to be generated in git.properties file. And because by default, all supported keys will be calculated, including the key  "git.build.time" which will change every time gradle building your code, so the file will be re-generated.

Can you try to limit to only the keys you want and see if it works for you? 
```
gitProperties {
    keys = ['git.branch','git.commit.id','git.commit.time']
}
```

**Comment by tha2015** [comment] 2019-07-13 03:31
I checked "maven git commit id" plugin and it seems this property "git.build.time"  also caused  issues for users. So I opened issue #129 to remove this property completely
