### ISSUE TITLE
RepositoryNotFoundException on jenkins

### ISSUE THREAD

**Issue by ezraroi** [n0mer/gradle-git-properties#45] opened 2018-01-14 14:56 UTC
When we upgraded from 1.4.17 to 1.4.20 we started to get this error on our jenkins server.
No sure why...
`
Execution failed for task ':service:generateGitProperties'.
> org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /tmp/jenkins/workspace/ApiGateway-pull-requests/.git/objects/c2
`

**Comment by n0mer** [comment] 2018-01-14 19:18
@ezraroi plugin works just fine for me. I use it together with gradle 4.2.11

Can you please try to do fresh check-out of project into another directory, and perform build from scratch there? Because for me it looks like some temporary files or permissions issue.

**Comment by ezraroi** [comment] 2018-01-14 19:55
Will check.. On the same files version 17 is working fine. Tested with gradle 4.4.1

**Comment by SanderDN** [comment] 2018-01-15 13:46
We're experiencing the same problem:

`Execution failed for task ':service:generateGitProperties'.
> org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /home/jenkins/workspace/PAS/Build/.git/hooks`

Reverting to version 17 also fixes the problem. We're using gradle 4.4.1.

**Comment by timkettering** [comment] 2018-01-16 22:34
Confirming this issue as well.  Jenkins builds fine when using plugin version 17, but version 20 breaks in Jenkins with the same error reported by others.

**Comment by gimlet2** [comment] 2018-01-18 10:29
I see the same locally

**Comment by damienbeaufils** [comment] 2018-01-22 14:28
Same issue here, with 1.4.20 and Gradle wrapper v4.4.1 on Linux Mint 18.2

**Comment by matei-dragu** [comment] 2018-01-24 13:40
Confirmed - version 1.4.20 + Gradle wrapper 4.4.1 on Linux 64bit:

> org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /home/jenkins/workspace/__PROJECT_NAME__/.git/logs

**Comment by napstr** [comment] 2018-02-09 01:43
My personal builds as well as CI server builds are fine, but after a recent update from .17 to .20 we have users reporting a failing build of a freshly checked out repo on 

> I'm using Ubuntu 16.04.3 LTS x64.

source: https://github.com/Frederikam/FredBoat/issues/460

**Comment by n0mer** [comment] 2018-02-27 23:33
fixed in https://github.com/n0mer/gradle-git-properties/issues/49#issuecomment-369065809

**Comment by n0mer** [comment] 2018-02-27 23:34
in some cases builds were working fine in gradle 4.2.1 , but failed in gradle 4.5.1

**Closed by n0mer** 2018-02-27 23:33 UTC
